### ISSUE TITLE
Cannot find module 'vue-router/auto'

### ISSUE THREAD

**Issue by rballonline** [vuetifyjs/create-vuetify#42]
I ran ```yarn create vuetify```

Options:

√ Which preset would you like to install? » Essentials (Base, Layouts, Pinia)
√ Use TypeScript? ... Yes
√ Would you like to install dependencies with yarn, npm, pnpm, or bun? » yarn

Tried running ```yarn build```

yarn run v1.22.21
$ vue-tsc --noEmit && vite build
src/router/index.ts:8:48 - error TS2307: Cannot find module 'vue-router/auto' or its corresponding type declarations.

8 import { createRouter, createWebHistory } from 'vue-router/auto'
                                                 ~~~~~~~~~~~~~~~~~

src/router/index.ts:9:30 - error TS2307: Cannot find module 'virtual:generated-layouts' or its corresponding type declarations.

9 import { setupLayouts } from 'virtual:generated-layouts'

```yarn dev``` seems to work, at least the one page is coming up correctly.

I was able to get the first error to clear by following some of the steps here: https://github.com/posva/unplugin-vue-router?tab=readme-ov-file#typescript although I have 0 clue if that's the correct thing to do.

**Comment by rballonline** [comment]
Possibly related to https://github.com/vuetifyjs/create-vuetify/issues/41

**Comment by wouterkroes** [comment]
I have found the fix: https://github.com/posva/unplugin-vue-router?tab=readme-ov-file#typescript

I guess `typed-router.d.ts` should be added to the `tsconfig.json` in the create-vuetify if you select typescript true

**Comment by jonaaldas** [comment]
> I have found the fix: https://github.com/posva/unplugin-vue-router?tab=readme-ov-file#typescript
> 
> I guess `typed-router.d.ts` should be added to the `tsconfig.json` by the create-vuetify if you select typescript true

I tried that fix and no luck. Maybe I am doing it wrong. Can you share your `tsconfig.json` file?

**Comment by wouterkroes** [comment]
Hmm, bummer to hear that.

I did nothing special, just add it to the include field as stated in the docs.
![image](https://github.com/vuetifyjs/create-vuetify/assets/6161307/2417e2e5-10d7-4ee5-a120-73261004e13a).

**Comment by Faeten** [comment]
does it fix  error TS2307: Cannot find module 'virtual:generated-layouts' or its corresponding type declarations. for you ? i fixed the first issue with typed-router but not this one.
and when you create a vuetify projet with the other preset the version shown is the last one, whereas essentials preset show 3.0.0

**Comment by juw177** [comment]
The virtual:generated-layouts issue is a missing option that needs to be added for vite-plugin-vue-layouts.
https://github.com/JohnCampionJr/vite-plugin-vue-layouts

{
  "compilerOptions": {
    "types": ["vite-plugin-vue-layouts/client"]
  }
}

**Comment by qizhou23** [comment]
@posva still have this problem with this config in tsconfig.json
```
{
  "include": [
    "./typed-router.d.ts"
  ],
  "compilerOptions": {
    "module": "ES2015",
    "moduleResolution": "Bundler",
    "types": [
      "unplugin-vue-router/client",
    ]
  },
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ],
}
```
any other config should I use ?

**Comment by qizhou23** [comment]
> @posva still have this problem with this config in tsconfig.json
> 
> ```
> {
>   "include": [
>     "./typed-router.d.ts"
>   ],
>   "compilerOptions": {
>     "module": "ES2015",
>     "moduleResolution": "Bundler",
>     "types": [
>       "unplugin-vue-router/client",
>     ]
>   },
>   "files": [],
>   "references": [
>     {
>       "path": "./tsconfig.node.json"
>     },
>     {
>       "path": "./tsconfig.app.json"
>     }
>   ],
> }
> ```
> 
> any other config should I use ?

but when I use this config and run `"run-p type-check \"build-only {@}\" --"` ,no error happened

**Comment by geraldmaale** [comment]
This `tsconfig.json` fixed my issues:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["ESNext", "DOM"],
    "skipLibCheck": true,
    "noEmit": true,
    "paths": {
      "@/*": ["src/*"]
    },
    "types": ["vite-plugin-vue-layouts/client", "node"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "typed-router.d.ts"
  ],
  "references": [{ "path": "./tsconfig.node.json" }],
  "exclude": ["node_modules"]
}
```

Note that changes were made to `types` and `include`.

**Comment by YSHgroup** [comment]
Hi everyone,
Your discussions on the issue gives me much assistance, but in my case, it didn't resolve the one.
So, I tried with other approach based on your discussions and resolved it.
Firstly, I created a new app with `npm create vuetify` command, thus could see the configuration you mentioned in `tsconfig.json` and `vite.config.mts` files from scratch.
in tsconfig.json:
```
...
"types": [
      "vite/client",
      "vite-plugin-vue-layouts/client",
      "unplugin-vue-router/client"
    ],
"include": [
    "./typed-router.d.ts"
  ],
...
```
in vite.config.mts
```
...
  plugins: [
    VueRouter({
      dts: 'src/typed-router.d.ts',
    }),
    Layouts(),
...
```
However, I got the typescript error like the following:
`Cannot find module 'vue-router/auto' or its corresponding type declarations.ts(2307)`

![image](https://github.com/vuetifyjs/create/assets/146746648/bfb76035-b97c-4338-81e2-d2391ae21751)

And then I noticed a point in `typed-router.d.ts`.
```
declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

```
Here, I replaced the `'vue-router/auto-routes'`  with `vue-router/auto'`
And then the typescript error doesn't appear anymore.
I just want my experience would be help to other developers who might face the same issue.

**Comment by TomZhong-au** [comment]
> This `tsconfig.json` fixed my issues:
> 
> ```json
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "target": "ESNext",
>     "useDefineForClassFields": true,
>     "module": "ESNext",
>     "moduleResolution": "Node",
>     "strict": true,
>     "jsx": "preserve",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "esModuleInterop": true,
>     "lib": ["ESNext", "DOM"],
>     "skipLibCheck": true,
>     "noEmit": true,
>     "paths": {
>       "@/*": ["src/*"]
>     },
>     "types": ["vite-plugin-vue-layouts/client", "node"]
>   },
>   "include": [
>     "src/**/*.ts",
>     "src/**/*.d.ts",
>     "src/**/*.tsx",
>     "src/**/*.vue",
>     "typed-router.d.ts"
>   ],
>   "references": [{ "path": "./tsconfig.node.json" }],
>   "exclude": ["node_modules"]
> }
> ```
> 
> Note that changes were made to `types` and `include`.

This did solve the issue.

**Comment by johnleider** [comment]
What install options are you using?
